### ISSUE TITLE
Ionic issue

### ISSUE THREAD

**Issue by alchemist1** [EddyVerbruggen/VideoCapturePlus-PhoneGap-Plugin#50]
I'm trying to install the plug-in and it gives me the error below

ionic cordova plugin add https://github.com/EddyVerbruggen/VideoC
apturePlus-PhoneGap-Plugin.git
> cordova plugin add https://github.com/EddyVerbruggen/VideoCapturePlus-PhoneGap-Plugin.git --save
✖ Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.

[ERROR] An error occurred while running cordova plugin add https://github.com/EddyVerbruggen/VideoCaptur
ePlus-PhoneGap-P... (exit code 1):

        You have been opted out of telemetry. To change this, run: cordova telemetry on.
        Error: Failed to fetch plugin https://github.com/EddyVerbruggen/VideoCapturePlus-PhoneGap-Plugin
.git via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 1 Error output:
        npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.orig
in.url
        npm WARN addRemoteGit
        npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
        npm WARN addRemoteGit     at emitTwo (events.js:106:13)
        npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
        npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
        npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:11)
        npm WARN addRemoteGit     at emitOne (events.js:96:13)
        npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
        npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:498:12)

**Comment by stefanotauriello** [comment]
Have you fixed it?

**Comment by alchemist1** [comment]
Nope. Dropped ionic. Best, Yoav.

**Comment by mitreya** [comment]
Hi, we have experienced the same error trying to add plugin on latest updated project ("Probably this is either a connection problem, or plugin spec is incorrect.") without ionic involved.
Is there some issue with new Cordova version?
Thank you.

**Comment by jaybloke** [comment]
I'm also having the same issue.... can get it installed, but whenever I do 'ionic cordova platform remove ios' and then 'ionic cordova platform add' then i always get a 404 for this plugin weird.

**Comment by evseevnn** [comment]
So what...? now body cannot solve it? no answer? @EddyVerbruggen Please help us...

**Comment by EddyVerbruggen** [comment]
@evseevnn Happy to merge a PR.

**Comment by Nauzer** [comment]
Can you try the fork in my account? I had some (similar) trouble with using in my Meteor project that I fixed for me specifically. If it works for Ionic as well I can submit a PR.

**Comment by presidentnickson** [comment]
Hey Nauzer, your fork has the same problem in ionic unfortunately !

`(node:70830) UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch plugin https://github.com/Nauzer/VideoCapturePlus-PhoneGap-Plugin via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json:
git+https://github.com/Nauzer/VideoCapturePlus-PhoneGap-Plugin.git.
npm ERR! package.json npm can't find a package.json file in your current directory.`

**Comment by Nauzer** [comment]
It looks like you are trying to install via npm registry. Try cordova plugin add https://github.com/Nauzer/VideoCapturePlus-PhoneGap-Plugin.git

**Comment by presidentnickson** [comment]
Unfortunately that generates the same error

**Comment by presidentnickson** [comment]
@Nauzer I've managed to get it working from this fork here https://github.com/danielsogl/cordova-plugin-video-capture-plus - is it perhaps the package.json that is needed?
